# -*- coding: utf-8 -*-
"""M5-(k-fold_cross_validation).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pT5RM4v_0SYndM4ApNRILkxTDWP2lNIG
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/heart.csv')

df

df.isnull().sum()

X=df.drop('output',axis=1)
y=df.output

from sklearn.model_selection import KFold,train_test_split,cross_val_score

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,r2_score

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

Kf=KFold(n_splits=5,shuffle=True)

reg=RandomForestRegressor()

reg.fit(X_train,y_train)

y_pred=reg.predict(X_test)

rscore=reg.score(X_train,y_train)

print(rscore)

cros_valscore=cross_val_score(reg,X,y,cv=5,scoring='r2')

print(cros_valscore)

Kf=KFold(n_splits=5,shuffle=True)

reg1=RandomForestRegressor()

score=[]

for i in range(5):
  result=next(Kf.split(X))
  X_train=X.iloc[result[0]]
  X_test=X.iloc[result[1]]
  y_train=y.iloc[result[0]]
  y_test=y.iloc[result[1]]

model=reg1.fit(X_train,y_train)

pred=reg1.predict(X_test)

score.append(model.score(X_test,y_test))

print('Score are: ',score)

print('Average_score: ',np.mean(score))